### ISSUE TITLE
Abstract to module.

### ISSUE THREAD

**Issue by xzovy** [xzovy/cryptographer.py#4]
Abstract out encryption operation into a module which can be imported into other programs.

**Comment by xzovy** [comment]
Added a bounty to get this fixed.
<a href="https://www.bountysource.com/issues/23099452-abstract-to-module?utm_source=23099452&utm_medium=shield&utm_campaign=ISSUE_BADGE"><img src="https://www.bountysource.com/badge/issue?issue_id=23099452" /></a>

**Comment by orchid-hybrid** [comment]
I've created a pull request which abstracts out the nonce generation, encryption algorithms and password hashing into it's own module. I've written up details on how that works here:

https://github.com/xzovy/cryptographer.py/pull/6

**Comment by xzovy** [comment]
Orchid-hybrid's solution works great. Good job!
